[testServer2]
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 2666dc437039c91a964936af93b29e18ec48d2da
BROKER_HOST = 172.24.1.2
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = DMZDatabaseEx
QUEUE = DMZDatabase
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

